trigger:
- main
 
pool:
vmImage: ubuntu-latest
 
steps:
 
- task: KubectlInstaller@0
inputs:
kubectlVersion: 'latest'
 
- task: AzureCLI@2
displayName: Connect to AKS
inputs:
azureSubscription: 'Azure-service-connection'
scriptType: bash
scriptLocation: inlineScript
inlineScript: |
az aks get-credentials --resource-group kubernetestest --name rajesh-aks --overwrite-existing
 
- script: |
kubectl apply -f deployment.yaml
kubectl apply -f service.yaml
displayName: Deploy to AKS