trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:

# Build and push Docker image
- task: Docker@2
  displayName: Build and Push Docker Image
  inputs:
    containerRegistry: docker-connection
    repository: rajeshbethireddy/rajesh-app
    command: buildAndPush
    Dockerfile: Dockerfile
    tags: |
      $(Build.BuildId)

# Connect to AKS
- task: AzureCLI@2
  displayName: Connect to AKS
  inputs:
    azureSubscription: aks-service-connection
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az aks get-credentials --resource-group kubernetestest --name rajesh-aks --overwrite-existing

# Deploy new image version to Kubernetes
- script: |
    kubectl set image deployment/rajesh-deployment rajesh-container=rajeshbethireddy/rajesh-app:$(Build.BuildId)
  displayName: Update Kubernetes Deployment